config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get :sort_jobs, controller: 'pages'
  resources :jobs, only: :create
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :id_char, uniqueness: true, length: { is: 1 }, presence: true
  validates :name, presence: true

  # next method is designed to order string of characters which represent jobs in db taking jobs which
  # are more important and moving them into left side of each character, main idea of solving the problem
  # is to use upgraded bubble sort 
  def self.order_by_dependencies(string)
    return string if string.size == 0
    if string.size == 1
      if job = Job.find_by(id_char: string)
        raise 'jobs can’t depend on themselves' if job.more_important_jobs.include?(string)
        return string
      else
        return ''
      end
    end
    swapped = true
    jobs = Job.where(id_char: string.split(''))
    number_of_circles = 0
    ##
    # Since in this problem circling without end is possible, the loop stops when it reaches max number of
    # circles and as error is raised
    while swapped && number_of_circles < string.size ** 2 + 1 do 
      swapped = false
      i = 0
      while i < string.size - 1
        if job = jobs.detect {|f| f[:id_char] == string[i]}
          if job.more_important_jobs.present?
            raise 'jobs can’t depend on themselves' if job.more_important_jobs.include?(string[i])
            # Next line takes common part of everything thats after current character and characters
            # which are more important then current
            chars_to_move = (string[i...string.size].chars & job.more_important_jobs.chars).join
            if chars_to_move.present?
              string.delete!(chars_to_move)
              string.insert(i, chars_to_move)
              i += chars_to_move.size # Possition of currently taken char moved after inserting
                                      # chars_to_move behind this char so i has so move ahead
              swapped = true
            end
          end
        else
          string.delete!(string[i]) # If variable jobs doesn't include currently taken char then the 
                                    # char doesn't represent any job so it has to be deleted
        end
        i+=1
      end
      number_of_circles += 1
    end
    # Loop ended because of reaching max number of circles and swap still was made then it raises error
    swapped ? raise('Dependencies circuled') : string
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def create
    @job = Job.new(job_params)
    if @job.save
      flash[:notice] = 'Job created'
      redirect_to root_path
    else
      flash[:danger] = 'Something went wrong try again'
      redirect_to root_path
    end
  end

  private
  def job_params
    params.require(:job).permit(:name, :id_char, :more_important_jobs)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @jobs = Job.paginate(:page => params[:page], :per_page => 20)
    @job = Job.new
  end

  def sort_jobs
    @string = Job.order_by_dependencies(sort_params[:string])
    @jobs = Job.paginate(:page => params[:page], :per_page => 20)
    @job = Job.new
    render 'home'
  end

  private
  def sort_params
    params.require(:sort_jobs).permit(:string)
  end

end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} &times;
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
= navbar fixed: :top do
  = navbar_header brand: 'Jobs'
  / = navbar_collapse do
  /   = navbar_group class: 'foo', id: 'menu' do
  /     = navbar_text 'Pick an option:'
  /     = navbar_item "Home", '/'
  /     = navbar_item "About Us", '/about-us'
  /     = navbar_item '/contact' do
  /       %span.glyphicon.glyphicon-hand-right
  /       Contact Us!
  /     = navbar_dropdown "Stuff" do
  /       = navbar_dropdown_header 'Great stuff!'
  /       = navbar_item "One", '/one'
  /       = navbar_item "Two", '/two'
  /       = navbar_item "Three", '/three'
  /       - if true # check if user is admin, maybe like "if current_user.try(:admin?)"
  /         = navbar_dropdown_divider
  /         = navbar_item "Admin Dashboard", '/admin'
  /         = navbar_item "Users", '/admin/users'
  /   = navbar_group align: 'right' do
  /     - if true # check if user is logged in, maybe like "if current_user.present?"
  /       = navbar_item "Log Out", '/logout'
  /     - else
  /       = navbar_item "Log In", '/login'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Jobs'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Jobs'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield
      = debug(params) if Rails.env.development?

app/views/pages/home.html.haml
- content_for :title do
  Home
%br
= simple_form_for(:sort_jobs, url: sort_jobs_path, method: 'get') do |f|
  = f.input :string, placeholder: 'Write here string of identificaiton characters of your jobs', label: false
  = f.button :submit, "Sort"
- if @string
  %h2 
    Here is your string - 
    %b= @string
%br
%center
  %h2 Create job
= simple_form_for(@job, url: jobs_path) do |f|
  = f.input :name, label: false, placeholder: 'Name'
  = f.input :id_char, label: false, placeholder: 'Identification character'
  = f.input :more_important_jobs, label: false, placeholder: 'Characters of more important jobs'
  = f.button :submit
%center
  %h2 All Jobs
%table.table
  %thead
    %tr
      %th Name
      %th Identification character
      %th More important jobs
  %tbody
    - @jobs.each do |job|
      %tr
        %td=job.name
        %td=job.id_char
        %td=job.more_important_jobs
%center= will_paginate @jobs, renderer: BootstrapPagination::Rails